SpectroDjango/urls.py
from django.contrib import admin
from django.urls import include,path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('blog.urls')),
    path('compute/',include('compute.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

blog/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'blog'

urlpatterns = [
    url(r'^$',views.post_list,name='post_list'),
    url(r'^(?P<year>\d{4})/(?P<month>\d{2})/(?P<day>\d{2})/(?P<post>[-\w]+)/$',views.post_detail,name='post_detail'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

compute/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'compute'

urlpatterns = [
    url(r'^$',views.elements,name='elements'),
    url(r"potentials/.*/channels$", views.channels, name='channels'),
    url(r"potentials/(?P<mass1>\d+\.\d+)/(?P<symbol1>\w+)/(?P<mass2>\d+\.\d+)/(?P<symbol2>\w+)/$", views.potentials, name='potentials'),
    url(r'files/$',views.view_files, name='files'),
    url(r"files/delete-(?P<id>\d)$", views.delete_file, name='delete_file'),
    url(r"files/(?P<id>\d)/$", views.file_detail, name='file_detail'),
    url(r'results/$',views.results, name='results'),
    url(r'results/delete-(?P<id>\d*)$',views.delete_result, name='delete_result'),
    url(r'results/download-(?P<id>\d*)$',views.download_result, name='download_result'),
    url(r'results/(?P<result_id>\d*)/$',views.result_detail, name='result_detail'),
    url(r'j_result-(?P<j_result_id>\d*)/$',views.j_result_detail, name='j_result_detail'),
    url('uploadfile', views.FileFieldView.as_view(), name='upload_file')
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

templates/base.html
<!doctype html>
<html lang="en">
  <head>
    {% load static %}
    
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="{% static "img/icon.png" %}">
     
    <title>{% block title %}{% endblock %} - sPYtroscopy  </title>
    <link
    href="https://cdn.pydata.org/bokeh/release/bokeh-0.12.13.min.css"
    rel="stylesheet" type="text/css">
    <link
    href="https://cdn.pydata.org/bokeh/release/bokeh-widgets-0.12.13.min.css"
    rel="stylesheet" type="text/css">
    <link
    href="https://cdn.pydata.org/bokeh/release/bokeh-tables-0.12.13.min.css"
    rel="stylesheet" type="text/css">
    
    <!-- Bootstrap core CSS -->
    <link rel="stylesheet" href="{% static "css/bootstrap.min.css" %}" >

    <!-- Custom styles for this template -->
    <link href="{% static "css/dashboard.css" %}" rel="stylesheet">

    

  </head>

  <body>

    <nav class="navbar navbar-inverse fixed-top bg-dark flex-md-nowrap p-0 shadow">
      <a class="navbar-brand col-sm-3 col-md-2 mr-0" href="{% url 'blog:post_list' %}">sPYtroscopy</a>
      <ul class="nav navbar-nav navbar-right">
        <li class="text-muted">
            {% if user.is_authenticated %}
            Signed in as, {{ user.username }}
            <a class="btn" href="{% url 'logout' %}"><span class="glyphicon glyphicon-log-in"></span>Log Out</a>
            {% else %}
            <a class="btn" href="{% url 'login' %}"><span class="glyphicon glyphicon-log-in"></span>Log In</a>
            {% endif %}
        </li>
      </ul>
    </nav>

    <div class="container-fluid">
      <div class="row">
        <nav class="bg-light sidebar col-2">
          <div class="sidebar-sticky">
            <ul class="nav flex-column">
              <li class="nav-item">
                <a class="nav-link" href="{% url 'blog:post_list' %}">
                  <span data-feather="home"></span>
                  Latest News
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'compute:files' %}">
                  <span data-feather="file"></span>
                  Files
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'compute:results'%}">
                  <span data-feather="bar-chart-2"></span>
                  Reports
                </a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'compute:elements' %}">
                  <span data-feather="layers"></span>
                  Compute
                </a>
              </li>
            </ul>

        
        </nav>
        
        <main role="main" class="col-md-9 ml-md-auto col-lg-10 px-4">
          <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
            {% block heading %}{% endblock %}  
          </div>
          {% block content %}{% endblock %}
        </main>
      </div>
    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <!--<script>window.jQuery || document.write('<script src="https://code.jquery.com/jquery-3.3.1.min.js"><\/script>')</script>-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.4.1/css/all.css" integrity="sha384-5sAR7xN1Nv6T6+dT2mhtzEpVJvfS3NScPQTrOxhwjIuvcA67KV2R5Jz6kr4abQsz" crossorigin="anonymous">  
    <!-- Icons -->
    <script src="https://unpkg.com/feather-icons/dist/feather.min.js"></script>
    <script>
      feather.replace()
    </script>
    {% block tail_js %}
    {% endblock %}
  </body>
</html>